---
seed: 42

model:
  architecture: inceptionv3
  num_classes: 1000
  pretrained: true

dataset:
  type: celeba_identities 
  validation_set_size: 0
  image_size: 299

transformations:
  RandomResizedCrop:
    size: [299, 299]
    ratio: [0.9, 1.1111]
    scale: [0.85, 1]
    ratio: [1, 1]
  ColorJitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.1
    hue: 0.1
  RandomHorizontalFlip:
    p: 0.5

optimizer:
  Adam:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0

lr_scheduler:
  MultiStepLR:
    milestones: [75, 90]
    gamma: 0.1

training:
  num_epochs: 100
  batch_size: 128
  dataloader_num_workers: 8
  save_path: results_eval/

rtpt:
  experiment_name: InceptionV3_CelebA
  name_initials: XX

wandb:
  enable_logging: true
  args:
    project: model_inversion_evaluation
    name: Inception_V3_CelebA
    save_code: true
